### ISSUE TITLE
URL code.google.com/p/memcached is dead

### ISSUE THREAD

**Issue by pascalandy** [bitnami/bitnami-docker-memcached#14]
https://code.google.com/p/memcached/wiki/NewConfiguringServer

**Comment by sameersbn** [comment]
@pascalandy we're unable to find an alternate location with the memcached docs. guess we should remove the link altogether :disappointed:

**Comment by sameersbn** [comment]
The referenced link was removed a while back. If you're looking for memcached docs, they can now be found at https://github.com/memcached/memcached/wiki. Closing this report, re-open if required.
