### ISSUE TITLE
Using with other containers on network

### ISSUE THREAD

**Issue by trainingcity** [bitnami/bitnami-docker-memcached#64]
Can you provide an example of how to configure other containers to access the bitnami memcached container on a docker network?

For example, if I bring up the memcached container using the following docker-compose.yml file, how do other containers, created using their own docker-compose.yml file, say running apache/wordpress, on the same docker network know to use memcached? 

Do I just need to add an environmental (MEMCACHED_HOST=memcached) variable to their respective docker-compose files, or do they need something else in their initial image setup?

memcached docker-compose file.

version: '3.1'
services:
  memcached:
    image: 'bitnami/memcached:latest'

    environment:
      - MEMCACHED_USERNAME= XXXXXX
      - MEMCACHED_PASSWORD=XXXXXX
      - MEMCACHED_CACHE_SIZE=1024

networks:
    default:
        external:
           name: mydockernet

**Comment by sameersbn** [comment]
@trainingcity Once you have the memcached server running on the docker network you would have to configure your application to use the memcached server.

For example, with wordpress you would have to install a cache plugin such as [w3 total cache](https://wordpress.org/plugins/w3-total-cache/) and configure it to communicate with the memcached server on the docker network.

**Comment by sameersbn** [comment]
@trainingcity do you have any updates?

**Comment by sameersbn** [comment]
closing the issue due to inactivity. Please re-open if you have any followup
