### ISSUE TITLE
/run.sh: line 28: cannot create temp file for here-document: Read-only file system

### ISSUE THREAD

**Issue by red-trela** [bitnami/bitnami-docker-memcached#68]
**Description**

**Steps to reproduce the issue:**

1. Deploy image on Kubernetes through Bitnami Memcached Helm Chart
2. Notice CrashLoopBackOff
3. Check Logs

**Describe the results you received:**

```
memcached 16:25:33.04 
memcached 16:25:33.05 Welcome to the Bitnami memcached container
memcached 16:25:33.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-memcached
memcached 16:25:33.05 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-memcached/issues
memcached 16:25:33.06 
memcached 16:25:33.06 INFO  ==> ** Starting Memcached setup **
memcached 16:25:33.09 INFO  ==> Initializing Memcached
memcached 16:25:33.10 INFO  ==> ** Memcached setup finished! **

/run.sh: line 28: cannot create temp file for here-document: Read-only file system
```

**Describe the results you expected:**

No error :)

**Additional information you deem important (e.g. issue happens only occasionally):**

Using version 1.6.9-debian-10-r27 (which is what's referenced in the example values-production.yaml of the helm chart), but I see no applicable change in newer versions either.

**Version**

No idea about the docker Version in this Kubernetes Cluster, sorry :(

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OpenShift 3

**Comment by red-trela** [comment]
Reproduced the issue with the latest version, 1.6.9-debian-10-r50

**Comment by javsalgar** [comment]
Hi,

It seems to me that you have a `ReadOnlyFilesystem` PodSecurityPolicy set in the cluster, causing all pods to follow a ReadOnlyFilesystem approach. Currently our containers are not compatible with `ReadOnlyFilesystem` environments. Could you double check that you have this policy enabled in your cluster?

**Comment by red-trela** [comment]
Ah, I thought that was supported, but I looked it up again and I probably somehow confused non-root with read-only :)

The Bitnami Helm Chart actually offers to start the pods with a `readOnlyRootFilesystem` (as their attribute is called) and they suggest to enable that for production. But in that case I'll have to report it there :)

Thanks for the feedback!

**Comment by javsalgar** [comment]
Hi,

Sorry, I did not see that memcached was one of the charts that support this feature. I tried deploying it with the feature enabled and found no issues. I confirm that it is a read-only filesystem. Could you provide more details about the Kubernetes platform you are using?

**Comment by red-trela** [comment]
Hm, that's weird. Sadly my cluster is quite old - OpenShift 3, Kubernetes 1.11.

**Comment by javsalgar** [comment]
Hi,

Are you able to try it in another Kubernetes platform?

**Comment by red-trela** [comment]
Unfortunately no. Actually, I'm not sure how you're not running into the issue with readOnlyRootFilesystem=true.

I also found the same issue reported towards another bitnami docker image, maybe their workaround would work here as well
https://github.com/bitnami/bitnami-docker-nginx/issues/139

I'll try to find time to give this a try today or tomorrow.

**Comment by red-trela** [comment]
Mounting an `emptyDir` on `/tmp` resolved the issue. Looking at the helm chart's templates, this actually happens in the two more common configuration cases: 1) "standalone" architecture, 2) "high-availability" architecture AND persistence **enabled**. However, there's what I'd call a bug, where no emptyDir is mounted in case 3) "high-availability" architecture AND persistence **disabled**.

So I think this image's behavior is understood / expected by the helm chart, but I'll report an issue wrt the third case in their repo.

**Comment by javsalgar** [comment]
Thank you very much for the input!
