### ISSUE TITLE
Not able to run image with MEMCACHED_LISTEN_ADDRESS environment variable

### ISSUE THREAD

**Issue by vigneshr35** [bitnami/bitnami-docker-memcached#69]
**Description**

I am not able to run image with MEMCACHED_LISTEN_ADDRESS environment variable using command shown below. As per my understanding from the documentation [here](https://github.com/memcached/memcached/wiki/ConfiguringServer#networking) and [here ](https://docs.oracle.com/cd/E17952_01/mysql-5.6-en/ha-memcached-cmdline-options.html), this is needed if our memcache instance will be accessed from remote application.
`docker run --name bitnami_memcached -e MEMCACHED_CACHE_SIZE=1000 -e MEMCACHED_PORT_NUMBER=11211 -e MEMCACHED_LISTEN_ADDRESS=<my_ip_address> bitnami/memcached:latest`

**Steps to reproduce the issue:**

1. Run image using command 
`docker run --name bitnami_memcached -e MEMCACHED_CACHE_SIZE=1000 -e MEMCACHED_PORT_NUMBER=11211 -e MEMCACHED_LISTEN_ADDRESS=<my_ip_address> bitnami/memcached:latest`

**Describe the results you received:**

I am getting error message as shown below

> memcached 05:40:23.00
> memcached 05:40:23.02 Welcome to the Bitnami memcached container
> memcached 05:40:23.02 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-memcached
> memcached 05:40:23.02 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-memcached/issues
> memcached 05:40:23.02
> memcached 05:40:23.02 INFO  ==> ** Starting Memcached setup **
> memcached 05:40:23.05 INFO  ==> Initializing Memcached
> memcached 05:40:23.05 INFO  ==> ** Memcached setup finished! **
> 
> memcached 05:40:23.07 INFO  ==> ** Starting Memcached **
> bind(): Cannot assign requested address
> failed to listen on TCP port 11211: Invalid argument

**Describe the results you expected:**

Memcached docker container successfully running on port 11211

**Additional information you deem important (e.g. issue happens only occasionally):**

NA

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1063-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.945GiB
 Name: Ansible
 ID: FOL5:6R26:VA2I:US53:UIVF:SJST:GKGI:3SI4:6N5P:VGCL:FOXH:RQLZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
NA
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @vigneshr35,

Could you check you don't have anything in port 11211?
```
 netstat -pna | grep 11211
```
