### ISSUE TITLE
connect and set get value

### ISSUE THREAD

**Issue by liyangshiren** [bitnami/bitnami-docker-memcached#71]
when config  auth info "MEMCACHED_USERNAME=my_user -e MEMCACHED_PASSWORD=my_password" how to use python memcache.Client connect and set get value

**Comment by alvneiayu** [comment]
hi @liyangshiren 

Maybe you can find something to solve your needs here:

https://realpython.com/python-memcache-efficient-caching/
https://pymemcache.readthedocs.io/en/latest/getting_started.html

Thanks a lot

Álvaro
