### ISSUE TITLE
saslpasswd2: generic failure

### ISSUE THREAD

**Issue by terryking93** [bitnami/bitnami-docker-memcached#72]
I have upgraded from bitnami/memcached:1.6.9-debian-10-r169 to 1.6.10 and now I am suddenly getting this error

saslpasswd2: generic failure

Unfortunately this is all the message I can get.

Also I attempted to go back to 1.6.9 but the latest release and I get the same error there as well.

**Comment by pablogalegoc** [comment]
Hi @terryking93!

Could you paste the command you are running to start the container or the `docker-compose.yml` that is giving you trouble? I tested some of the examples in the README and couldn't see the error message. Thanks!

**Comment by terryking93** [comment]
So this is running via the bitnami helm chart

**Comment by terryking93** [comment]
So I see the problem, just not sure why though.. when I add a username/password to the values in the helm chart.. this error occurs

**Comment by pablogalegoc** [comment]
Hey @terryking93,

I’ve installed the latest version of the chart setting `1.6.9-debian-10-r169` then upgraded to `1.6.10-debian-10-r0` but couldn’t get the error message. Which chart version are you using? Are you able to reproduce the error on a fresh install?

**Comment by terryking93** [comment]
I am using the latest helm chart and the latest image.  I noticed it only occurs when I set a value for the user an password in the values file.  With no username password I have no issues.

**Comment by terryking93** [comment]
Also yes, I tried a different K8s cluster and was able to see the same issue

**Comment by pablogalegoc** [comment]
Unfortunately I’m still unable to reproduce the issue. Could you please set the following values:
```yaml
image:
  debug: true
memcachedUsername: “testuser”
memcachedPassword: “testpassword”
```
and share the outputs of `kubectl describe` and `kubectl logs` of the memcached pod? Maybe enabling the debug mode we can see a hint
