### ISSUE TITLE
missing aarch64 based image

### ISSUE THREAD

**Issue by volker-raschek** [bitnami/bitnami-docker-memcached#73]
**Description** 

I added a aarch64 node into my cluster. Since a rescale of gitea, which has an optional dependency to memcache, memcache throws an exec format error:

```bash
$ kubectl logs gitea-memcached-864dd9c97f-z5qgn 
exec /opt/bitnami/scripts/memcached/entrypoint.sh: exec format error
```

The best solution is to provide an aarch64 and armv7 image of memcache. I have made the suggestion to the gitea team that as long as there is no image for aarch64 and armv7 the rollout should be restricted to arm64 based nodes. 

[gitea issue](https://gitea.com/gitea/helm-chart/issues/285)

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. There are plans to add arm support to our images, but not in the immediate short term. As soon as there are updates, we will update this ticket.

**Comment by samip5** [comment]
There is already an issue regarding this: https://github.com/bitnami/charts/issues/7305

**Comment by volker-raschek** [comment]
Hi @samip5, 
thanks for the reference to the other issue. I close this issue
