### ISSUE TITLE
Config/env variable for item size

### ISSUE THREAD

**Issue by jirkace** [bitnami/bitnami-docker-memcached#74]
### Name and Version

bitnami/memcached:latest (6890ac6908e9)

### What is the problem this feature will solve?

Hi, I need to adjust `max item size` for running Memcached. I tried to add config with custom docker image overlay (`ADD memcached.conf /opt/bitnami/memcached/conf/memcached.conf`) but without any effect.

My app is logging an error:

`MemcachePool::set(): Server memcache.testing.svc.cluster.local (tcp 11211, udp 0) failed with: SERVER_ERROR object too large for cache (3)`

I believe, that my issue is default `max-item-size` value as 1m, on our production servers is it set to 8m.

```
-I, --max-item-size=<num> adjusts max item size
                          (default: 1m, min: 1k, max: 1024m)
```

### What is the feature you are proposing to solve the problem?

Bigger data item correctly saved into memcache.

**Comment by javsalgar** [comment]
Hi,

I see that you have a fork, would you like to submit a PR with the contribution?

**Comment by jirkace** [comment]
@javsalgar Hi, I did it a few minutes after submit this issue... see #75

**Comment by juan131** [comment]
Fixed at https://github.com/bitnami/bitnami-docker-memcached/pull/75
